export const initialState = {
  user: {
    username: null,
    filial: null,
    controller: null,
  },
  opData: {
    codigo: null,
    codbel: null,
    dtvalidade: null,
    filial: null,
    lote: null,
    op: null,
    produto: null,
    qtdpad: null,
  },
  apData: {
    id: null,
    codigo: null,
    dt_fim: null,
    dt_inicio: null,
    dtvalidade: null,
    filial: null,
    hr_fim: null,
    hr_inicio: null,
    lote: null,
    numero: null,
    op: null,
    produto: null,
    quantidade: null,
    usuario: null,
  },
};
